### ISSUE TITLE
Parameter value capitalization

### ISSUE THREAD

**Issue by DanGiffen** [terraform-azurerm-modules/terraform-azurerm-azopsreference#35]
**Describe the bug**
Module and definitions deployed fine. 
Any subsequent plans include 84 changes for the parameter values to be changed e.g. "String" to "string". The value is lower case in the source TF definitions and I assume the Azure platform capitalizes it once pushed.

You can amend manually in the local module files as a workaround.

**Steps to reproduce**

1.
2.

**Screenshots**
![image](https://user-images.githubusercontent.com/38534725/112586793-5014a900-8df4-11eb-841c-55853df44617.png)

![image](https://user-images.githubusercontent.com/38534725/112586824-628ee280-8df4-11eb-84d9-98c761bf7108.png)

**Comment by matt-FFFFFF** [comment]
Hi, apologies for the delay on this. I didn't receive a notification. The issue was upstream in the ES repo but I understand that this is fixed now. I'll release a new version with the latest.

**Comment by DanGiffen** [comment]
No problem, thanks for the update Matt. Will keep an eye out for the new release. 

Cheers
Dan

**Comment by matt-FFFFFF** [comment]
v0.11 out now containing latest from upstream

**Comment by matt-FFFFFF** [comment]
Closing, please re-open if you are still affected
